In [11]:
# 4月・5月・6月各シートのデータを結合する
import pandas as pd

month_list=["4月","5月","6月"]

df_concat=pd.DataFrame()

for month in month_list:
    df_m=pd.read_excel("月別売上.xlsx",sheet_name=month)
    df_concat=pd.concat([df_concat,df_m])

df_concat

    No.        取引日       取引先     社員番号    商品名     単価  個数
0     1 2022-04-01  テスト１株式会社  1100000  キーボード   6000   1
1     2 2022-04-02  テスト２株式会社  1200000  タブレット  50000   1
2     3 2022-04-03  テスト２株式会社  1400000  タブレット  50000   4
3     4 2022-04-04  テスト３株式会社  1300000  キーボード   6000   2
4     5 2022-04-05  テスト１株式会社  1100000  タブレット  50000   4
..  ...        ...       ...      ...    ...    ...  ..
25   26 2022-06-26  テスト３株式会社  1400000  キーボード   6000   2
26   27 2022-06-27  テスト２株式会社  1100000  キーボード   6000   3
27   28 2022-06-28  テスト２株式会社  1200000  キーボード   6000   4
28   29 2022-06-29  テスト１株式会社  1200000  キーボード   6000   3
29   30 2022-06-30  テスト１株式会社  1200000  タブレット  50000   1

[91 rows x 7 columns]

In [16]:
# 売上金額の列追加

df_concat["売上金額"]=df_concat["単価"]*df_concat["個数"]
df_concat

    No.        取引日       取引先     社員番号    商品名     単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  1100000  キーボード   6000   1    6000
1     2 2022-04-02  テスト２株式会社  1200000  タブレット  50000   1   50000
2     3 2022-04-03  テスト２株式会社  1400000  タブレット  50000   4  200000
3     4 2022-04-04  テスト３株式会社  1300000  キーボード   6000   2   12000
4     5 2022-04-05  テスト１株式会社  1100000  タブレット  50000   4  200000
..  ...        ...       ...      ...    ...    ...  ..     ...
25   26 2022-06-26  テスト３株式会社  1400000  キーボード   6000   2   12000
26   27 2022-06-27  テスト２株式会社  1100000  キーボード   6000   3   18000
27   28 2022-06-28  テスト２株式会社  1200000  キーボード   6000   4   24000
28   29 2022-06-29  テスト１株式会社  1200000  キーボード   6000   3   18000
29   30 2022-06-30  テスト１株式会社  1200000  タブレット  50000   1   50000

[91 rows x 8 columns]

In [17]:
# 担当者列を追加

df_s=pd.read_excel("社員リスト.xlsx")
df_s

        社員番号  名前
0  A-1100000  田中
1  A-1200000  佐藤
2  B-1300000  鈴木
3  B-1400000  中村

In [18]:
df_s["社員番号"]=df_s["社員番号"].str.replace("A-","").str.replace("B-","")
df_s

      社員番号  名前
0  1100000  田中
1  1200000  佐藤
2  1300000  鈴木
3  1400000  中村

In [ ]:
df_merge=pd.merge(df_concat,df_s,on="社員番号")

In [19]:
df_s=df_s.astype({"社員番号":int})
df_s

      社員番号  名前
0  1100000  田中
1  1200000  佐藤
2  1300000  鈴木
3  1400000  中村

In [20]:
df_merge=pd.merge(df_concat,df_s,on="社員番号")
df_merge

    No.        取引日       取引先     社員番号    商品名     単価  個数    売上金額  名前
0     1 2022-04-01  テスト１株式会社  1100000  キーボード   6000   1    6000  田中
1     2 2022-04-02  テスト２株式会社  1200000  タブレット  50000   1   50000  佐藤
2     3 2022-04-03  テスト２株式会社  1400000  タブレット  50000   4  200000  中村
3     4 2022-04-04  テスト３株式会社  1300000  キーボード   6000   2   12000  鈴木
4     5 2022-04-05  テスト１株式会社  1100000  タブレット  50000   4  200000  田中
..  ...        ...       ...      ...    ...    ...  ..     ...  ..
86   26 2022-06-26  テスト３株式会社  1400000  キーボード   6000   2   12000  中村
87   27 2022-06-27  テスト２株式会社  1100000  キーボード   6000   3   18000  田中
88   28 2022-06-28  テスト２株式会社  1200000  キーボード   6000   4   24000  佐藤
89   29 2022-06-29  テスト１株式会社  1200000  キーボード   6000   3   18000  佐藤
90   30 2022-06-30  テスト１株式会社  1200000  タブレット  50000   1   50000  佐藤

[91 rows x 9 columns]

In [21]:
# 担当者別に分ける

df_each=df_merge[df_merge["名前"]=="田中"]
df_each

    No.        取引日       取引先     社員番号    商品名      単価  個数    売上金額  名前
0     1 2022-04-01  テスト１株式会社  1100000  キーボード    6000   1    6000  田中
4     5 2022-04-05  テスト１株式会社  1100000  タブレット   50000   4  200000  田中
7     8 2022-04-08  テスト１株式会社  1100000  タブレット   50000   2  100000  田中
8     9 2022-04-09  テスト１株式会社  1100000  タブレット   50000   2  100000  田中
11   12 2022-04-12  テスト１株式会社  1100000     PC  100000   2  200000  田中
14   15 2022-04-15  テスト１株式会社  1100000  タブレット   50000   5  250000  田中
16   17 2022-04-17  テスト２株式会社  1100000     PC  100000   1  100000  田中
17   18 2022-04-18  テスト２株式会社  1100000     PC  100000   4  400000  田中
22   23 2022-04-23  テスト２株式会社  1100000    マウス    1500   2    3000  田中
23   24 2022-04-24  テスト１株式会社  1100000     PC  100000   4  400000  田中
25   26 2022-04-26  テスト２株式会社  1100000  キーボード    6000   3   18000  田中
37    8 2022-05-08  テスト１株式会社  1100000  タブレット   50000   1   50000  田中
42   13 2022-05-13  テスト１株式会社  1100000  キーボード    6000   3   18000  田中
43   14 2022-05-14  テスト１株式会社  1100000  タブレット   50000   2  100000  田中
44   15 2022-05-15  テスト２株式会社  1100000  タブレット   50000   5  250000  田中
45   16 2022-05-16  テスト２株式会社  1100000  タブレット   50000   5  250000  田中
46   17 2022-05-17  テスト２株式会社  1100000    マウス    1500   4    6000  田中
53   24 2022-05-24  テスト１株式会社  1100000    マウス    1500   5    7500  田中
57   28 2022-05-28  テスト２株式会社  1100000  タブレット   50000   4  200000  田中
71   11 2022-06-11  テスト１株式会社  1100000  キーボード    6000   4   24000  田中
76   16 2022-06-16  テスト１株式会社  1100000  タブレット   50000   3  150000  田中
79   19 2022-06-19  テスト２株式会社  1100000    マウス    1500   1    1500  田中
80   20 2022-06-20  テスト１株式会社  1100000     PC  100000   4  400000  田中
85   25 2022-06-25  テスト１株式会社  1100000    マウス    1500   4    6000  田中
87   27 2022-06-27  テスト２株式会社  1100000  キーボード    6000   3   18000  田中

In [24]:
# pivot

df_output=df_each.pivot_table(index="取引先",columns="商品名",values="売上金額",aggfunc="sum",fill_value=0,margins=True,margins_name="総計")
df_output

商品名            PC  キーボード    タブレット    マウス       総計
取引先
テスト１株式会社  1000000  48000   950000  13500  2011500
テスト２株式会社   500000  36000   700000  10500  1246500
総計        1500000  84000  1650000  24000  3258000

In [26]:
# 完成版
import pandas as pd

month_list=["4月","5月","6月"]

df_concat=pd.DataFrame()

for month in month_list:
    df_m=pd.read_excel("月別売上.xlsx",sheet_name=month)
    df_concat=pd.concat([df_concat,df_m])

df_concat["売上金額"]=df_concat["単価"]*df_concat["個数"]

df_s=pd.read_excel("社員リスト.xlsx",sheet_name="リスト")

df_s["社員番号"]=df_s["社員番号"].str.replace("A-","").str.replace("B-","")

df_s=df_s.astype({"社員番号":int})

df_merge=pd.merge(df_concat,df_s,on="社員番号")

name_list=df_merge["名前"].unique()

for name in name_list:
    df_each=df_merge[df_merge["名前"]==name]
    df_output=df_each.pivot_table(index="取引先",columns="商品名",values="売上金額",aggfunc="sum",fill_value=0,margins=True,margins_name="総計")
    df_output.to_excel("総売上内訳_{}.xlsx".format(name))