In [ ]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("売上一覧.xlsx",sheet_name="Sheet1")
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  中村  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df["売上金額"]

0       6000
1      50000
2     200000
3      12000
4     200000
       ...
95     12000
96    500000
97     30000
98      3000
99    300000
Name: 売上金額, Length: 100, dtype: int64

In [7]:
type(df["売上金額"])

pandas.core.series.Series

In [8]:
df["売上金額"].sum()

np.int64(13697000)

In [9]:
df["売上金額"].mean()

np.float64(136970.0)

In [10]:
df["売上金額"].count()

np.int64(100)

In [12]:
df[["担当者","売上金額"]]

   担当者    売上金額
0   田中    6000
1   佐藤   50000
2   中村  200000
3   鈴木   12000
4   田中  200000
..  ..     ...
95  佐藤   12000
96  佐藤  500000
97  鈴木   30000
98  佐藤    3000
99  佐藤  300000

[100 rows x 2 columns]

In [13]:
df.iloc[2,3]

'中村'

In [15]:
df.iloc[2,3]="OUCHI"
df

    No.        取引日       取引先    担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社     田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社     佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  OUCHI  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社     鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社     田中  タブレット   50000   4  200000
..  ...        ...       ...    ...    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社     佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社     佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社     鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社     佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社     佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [16]:
df.iloc[1:4,0:3]

   No.        取引日       取引先
1    2 2022-04-02  テスト２株式会社
2    3 2022-04-03  テスト２株式会社
3    4 2022-04-04  テスト３株式会社

In [18]:
df.iloc[1:4,[0,2]]

   No.       取引先
1    2  テスト２株式会社
2    3  テスト２株式会社
3    4  テスト３株式会社

In [19]:
df.iloc[1:4,:]

   No.        取引日       取引先    担当者    商品名     単価  個数    売上金額
1    2 2022-04-02  テスト２株式会社     佐藤  タブレット  50000   1   50000
2    3 2022-04-03  テスト２株式会社  OUCHI  タブレット  50000   4  200000
3    4 2022-04-04  テスト３株式会社     鈴木  キーボード   6000   2   12000

In [20]:
df.iloc[:,0:3]

    No.        取引日       取引先
0     1 2022-04-01  テスト１株式会社
1     2 2022-04-02  テスト２株式会社
2     3 2022-04-03  テスト２株式会社
3     4 2022-04-04  テスト３株式会社
4     5 2022-04-05  テスト１株式会社
..  ...        ...       ...
95   96 2022-07-05  テスト１株式会社
96   97 2022-07-06  テスト１株式会社
97   98 2022-07-07  テスト３株式会社
98   99 2022-07-08  テスト２株式会社
99  100 2022-07-09  テスト１株式会社

[100 rows x 3 columns]

In [21]:
df.iloc[:,[3,7]]

      担当者    売上金額
0      田中    6000
1      佐藤   50000
2   OUCHI  200000
3      鈴木   12000
4      田中  200000
..    ...     ...
95     佐藤   12000
96     佐藤  500000
97     鈴木   30000
98     佐藤    3000
99     佐藤  300000

[100 rows x 2 columns]

In [24]:
df["商品名"]=df["商品名"].str.replace("PC","パソコン")

In [25]:
df

    No.        取引日       取引先    担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社     田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社     佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  OUCHI  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社     鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社     田中  タブレット   50000   4  200000
..  ...        ...       ...    ...    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社     佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社     佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社     鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社     佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社     佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]

In [26]:
df["商品名"]=df["商品名"].str.replace("ボード","ぼーど")
df

    No.        取引日       取引先    担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社     田中  キーぼーど    6000   1    6000
1     2 2022-04-02  テスト２株式会社     佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  OUCHI  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社     鈴木  キーぼーど    6000   2   12000
4     5 2022-04-05  テスト１株式会社     田中  タブレット   50000   4  200000
..  ...        ...       ...    ...    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社     佐藤  キーぼーど    6000   2   12000
96   97 2022-07-06  テスト１株式会社     佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社     鈴木  キーぼーど    6000   5   30000
98   99 2022-07-08  テスト２株式会社     佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社     佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]

In [27]:
df["商品名"]=df["商品名"].str.replace("レット","")
df

    No.        取引日       取引先    担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社     田中  キーぼーど    6000   1    6000
1     2 2022-04-02  テスト２株式会社     佐藤     タブ   50000   1   50000
2     3 2022-04-03  テスト２株式会社  OUCHI     タブ   50000   4  200000
3     4 2022-04-04  テスト３株式会社     鈴木  キーぼーど    6000   2   12000
4     5 2022-04-05  テスト１株式会社     田中     タブ   50000   4  200000
..  ...        ...       ...    ...    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社     佐藤  キーぼーど    6000   2   12000
96   97 2022-07-06  テスト１株式会社     佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社     鈴木  キーぼーど    6000   5   30000
98   99 2022-07-08  テスト２株式会社     佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社     佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]