# VLOOKUP

In [1]:
import pandas as pd

df=pd.read_csv("問い合わせ履歴_4月末時点.csv",encoding="shift-jis")
df

         ID                 発生日時       取引先 担当者     社員番号  カテゴリ   内容  対応工数(h)
0   4_10001  2022-04-17 16:35:07  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.5
1   4_10002  2022-04-25 16:53:39  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
2   4_10003  2022-04-09 16:04:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
3   4_10004  2022-04-21 23:15:13  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
4   4_10005  2022-04-08 12:59:55  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
5   4_10006  2022-04-15 17:11:47  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0
6   4_10007  2022-04-13 00:57:33  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
7   4_10008  2022-04-17 00:15:48  テスト１株式会社  鈴木  1300000  使用方法  ・・・      0.5
8   4_10009  2022-04-08 15:02:22  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
9   4_10010  2022-04-21 07:45:41  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
10  4_10011  2022-04-29 20:29:25  テスト１株式会社  田中  1100000  使用方法  ・・・      1.0
11  4_10012  2022-04-30 06:22:19  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
12  4_10013  2022-04-05 21:10:47  テスト３株式会社  佐藤  1200000   その他  ・・・      1.0
13  4_10014  2022-04-23 14:23:50  テスト１株式会社  田中  1100000   その他  ・・・      1.5
14  4_10015  2022-04-02 02:27:56  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
15  4_10016  2022-04-09 00:13:31  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
16  4_10017  2022-04-08 23:27:21  テスト２株式会社  中村  1400000  契約内容  ・・・      0.5
17  4_10018  2022-04-28 15:54:55  テスト２株式会社  中村  1400000   その他  ・・・      1.0
18  4_10019  2022-04-24 11:48:17  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
19  4_10020  2022-04-10 13:45:33  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
20  4_10021  2022-04-19 20:00:11  テスト１株式会社  佐藤  1200000  使用方法  ・・・      1.0
21  4_10022  2022-04-03 07:12:07  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.0
22  4_10023  2022-04-14 21:33:52  テスト３株式会社  田中  1100000  使用方法  ・・・      0.5
23  4_10024  2022-04-22 15:38:34  テスト１株式会社  鈴木  1300000  使用方法  ・・・      2.0
24  4_10025  2022-04-02 13:34:11  テスト２株式会社  佐藤  1200000  契約内容  ・・・      1.5
25  4_10026  2022-04-21 08:28:44  テスト１株式会社  中村  1400000  契約内容  ・・・      2.0
26  4_10027  2022-04-26 07:48:02  テスト３株式会社  佐藤  1200000  使用方法  ・・・      1.0
27  4_10028  2022-04-29 07:43:31  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
28  4_10029  2022-04-23 14:37:18  テスト１株式会社  田中  1100000  契約内容  ・・・      0.5
29  4_10030  2022-04-02 23:13:24  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5

In [3]:
df2=pd.read_excel("所属部署リスト.xlsx",sheet_name="Sheet1")
df2

      社員番号  名前     部署
0  1100000  田中  第1営業部
1  1200000  佐藤  第1営業部
2  1300000  鈴木  第2営業部
3  1400000  中村  第2営業部

In [8]:
df_merge=pd.merge(df,df2,on="社員番号")
df_merge.iloc[:,[0,1,2,9,3,4,5,6,7]].sort_values("ID")

,ID,発生日時,取引先,部署,担当者,社員番号,カテゴリ,内容,対応工数(h)
0,4_10001,2022-04-17 16:35:07,テスト１株式会社,第2営業部,鈴木,1300000,契約内容,・・・,1.5
1,4_10002,2022-04-25 16:53:39,テスト３株式会社,第1営業部,佐藤,1200000,契約内容,・・・,0.5
2,4_10003,2022-04-09 16:04:13,テスト１株式会社,第1営業部,田中,1100000,使用方法,・・・,1.5
3,4_10004,2022-04-21 23:15:13,テスト１株式会社,第2営業部,鈴木,1300000,使用方法,・・・,1.0
4,4_10005,2022-04-08 12:59:55,テスト３株式会社,第2営業部,鈴木,1300000,その他,・・・,2.0
5,4_10006,2022-04-15 17:11:47,テスト２株式会社,第2営業部,鈴木,1300000,契約内容,・・・,1.0
6,4_10007,2022-04-13 00:57:33,テスト２株式会社,第2営業部,中村,1400000,契約内容,・・・,1.0
7,4_10008,2022-04-17 00:15:48,テスト１株式会社,第2営業部,鈴木,1300000,使用方法,・・・,0.5
8,4_10009,2022-04-08 15:02:22,テスト１株式会社,第1営業部,佐藤,1200000,その他,・・・,1.5
9,4_10010,2022-04-21 07:45:41,テスト３株式会社,第1営業部,佐藤,1200000,契約内容,・・・,0.5
10,4_10011,2022-04-29 20:29:25,テスト１株式会社,第1営業部,田中,1100000,使用方法,・・・,1.0
11,4_10012,2022-04-30 06:22:19,テスト１株式会社,第2営業部,鈴木,1300000,使用方法,・・・,1.0
12,4_10013,2022-04-05 21:10:47,テスト３株式会社,第1営業部,佐藤,1200000,その他,・・・,1.0
13,4_10014,2022-04-23 14:23:50,テスト１株式会社,第1営業部,田中,1100000,その他,・・・,1.5
14,4_10015,2022-04-02 02:27:56,テスト１株式会社,第2営業部,鈴木,1300000,契約内容,・・・,2.0
15,4_10016,2022-04-09 00:13:31,テスト１株式会社,第1営業部,田中,1100000,使用方法,・・・,1.5
16,4_10017,2022-04-08 23:27:21,テスト２株式会社,第2営業部,中村,1400000,契約内容,・・・,0.5
17,4_10018,2022-04-28 15:54:55,テスト２株式会社,第2営業部,中村,1400000,その他,・・・,1.0
18,4_10019,2022-04-24 11:48:17,テスト２株式会社,第2営業部,中村,1400000,契約内容,・・・,1.0
19,4_10020,2022-04-10 13:45:33,テスト３株式会社,第2営業部,鈴木,1300000,その他,・・・,2.0
20,4_10021,2022-04-19 20:00:11,テスト１株式会社,第1営業部,佐藤,1200000,使用方法,・・・,1.0
21,4_10022,2022-04-03 07:12:07,テスト２株式会社,第2営業部,鈴木,1300000,使用方法,・・・,1.0
22,4_10023,2022-04-14 21:33:52,テスト３株式会社,第1営業部,田中,1100000,使用方法,・・・,0.5
23,4_10024,2022-04-22 15:38:34,テスト１株式会社,第2営業部,鈴木,1300000,使用方法,・・・,2.0
24,4_10025,2022-04-02 13:34:11,テスト２株式会社,第1営業部,佐藤,1200000,契約内容,・・・,1.5
25,4_10026,2022-04-21 08:28:44,テスト１株式会社,第2営業部,中村,1400000,契約内容,・・・,2.0
26,4_10027,2022-04-26 07:48:02,テスト３株式会社,第1営業部,佐藤,1200000,使用方法,・・・,1.0
27,4_10028,2022-04-29 07:43:31,テスト１株式会社,第2営業部,鈴木,1300000,契約内容,・・・,2.0
28,4_10029,2022-04-23 14:37:18,テスト１株式会社,第1営業部,田中,1100000,契約内容,・・・,0.5
29,4_10030,2022-04-02 23:13:24,テスト１株式会社,第1営業部,田中,1100000,使用方法,・・・,1.5

In [13]:
# 完成版

import pandas as pd

df=pd.read_csv("問い合わせ履歴_4月末時点.csv",encoding="shift-jis")
df2=pd.read_excel("所属部署リスト.xlsx",sheet_name="Sheet1")

df_merge=pd.merge(df,df2,on="社員番号")
df_merge.iloc[:,[0,1,2,9,3,4,5,6,7]].sort_values("ID")

df_merge.to_csv("問い合わせ履歴_4月末時点_部署追記.csv",encoding="shift-jis",index=False)

In [14]:
df_merge2=pd.merge(df,df2,left_on="担当者",right_on="名前")
df_merge2

,ID,発生日時,取引先,担当者,社員番号_x,カテゴリ,内容,対応工数(h),社員番号_y,名前,部署
0,4_10001,2022-04-17 16:35:07,テスト１株式会社,鈴木,1300000,契約内容,・・・,1.5,1300000,鈴木,第2営業部
1,4_10002,2022-04-25 16:53:39,テスト３株式会社,佐藤,1200000,契約内容,・・・,0.5,1200000,佐藤,第1営業部
2,4_10003,2022-04-09 16:04:13,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部
3,4_10004,2022-04-21 23:15:13,テスト１株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
4,4_10005,2022-04-08 12:59:55,テスト３株式会社,鈴木,1300000,その他,・・・,2.0,1300000,鈴木,第2営業部
5,4_10006,2022-04-15 17:11:47,テスト２株式会社,鈴木,1300000,契約内容,・・・,1.0,1300000,鈴木,第2営業部
6,4_10007,2022-04-13 00:57:33,テスト２株式会社,中村,1400000,契約内容,・・・,1.0,1400000,中村,第2営業部
7,4_10008,2022-04-17 00:15:48,テスト１株式会社,鈴木,1300000,使用方法,・・・,0.5,1300000,鈴木,第2営業部
8,4_10009,2022-04-08 15:02:22,テスト１株式会社,佐藤,1200000,その他,・・・,1.5,1200000,佐藤,第1営業部
9,4_10010,2022-04-21 07:45:41,テスト３株式会社,佐藤,1200000,契約内容,・・・,0.5,1200000,佐藤,第1営業部
10,4_10011,2022-04-29 20:29:25,テスト１株式会社,田中,1100000,使用方法,・・・,1.0,1100000,田中,第1営業部
11,4_10012,2022-04-30 06:22:19,テスト１株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
12,4_10013,2022-04-05 21:10:47,テスト３株式会社,佐藤,1200000,その他,・・・,1.0,1200000,佐藤,第1営業部
13,4_10014,2022-04-23 14:23:50,テスト１株式会社,田中,1100000,その他,・・・,1.5,1100000,田中,第1営業部
14,4_10015,2022-04-02 02:27:56,テスト１株式会社,鈴木,1300000,契約内容,・・・,2.0,1300000,鈴木,第2営業部
15,4_10016,2022-04-09 00:13:31,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部
16,4_10017,2022-04-08 23:27:21,テスト２株式会社,中村,1400000,契約内容,・・・,0.5,1400000,中村,第2営業部
17,4_10018,2022-04-28 15:54:55,テスト２株式会社,中村,1400000,その他,・・・,1.0,1400000,中村,第2営業部
18,4_10019,2022-04-24 11:48:17,テスト２株式会社,中村,1400000,契約内容,・・・,1.0,1400000,中村,第2営業部
19,4_10020,2022-04-10 13:45:33,テスト３株式会社,鈴木,1300000,その他,・・・,2.0,1300000,鈴木,第2営業部
20,4_10021,2022-04-19 20:00:11,テスト１株式会社,佐藤,1200000,使用方法,・・・,1.0,1200000,佐藤,第1営業部
21,4_10022,2022-04-03 07:12:07,テスト２株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
22,4_10023,2022-04-14 21:33:52,テスト３株式会社,田中,1100000,使用方法,・・・,0.5,1100000,田中,第1営業部
23,4_10024,2022-04-22 15:38:34,テスト１株式会社,鈴木,1300000,使用方法,・・・,2.0,1300000,鈴木,第2営業部
24,4_10025,2022-04-02 13:34:11,テスト２株式会社,佐藤,1200000,契約内容,・・・,1.5,1200000,佐藤,第1営業部
25,4_10026,2022-04-21 08:28:44,テスト１株式会社,中村,1400000,契約内容,・・・,2.0,1400000,中村,第2営業部
26,4_10027,2022-04-26 07:48:02,テスト３株式会社,佐藤,1200000,使用方法,・・・,1.0,1200000,佐藤,第1営業部
27,4_10028,2022-04-29 07:43:31,テスト１株式会社,鈴木,1300000,契約内容,・・・,2.0,1300000,鈴木,第2営業部
28,4_10029,2022-04-23 14:37:18,テスト１株式会社,田中,1100000,契約内容,・・・,0.5,1100000,田中,第1営業部
29,4_10030,2022-04-02 23:13:24,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部

In [15]:
df_merge2.rename(columns={"社員番号_x":"社員番号"})

,ID,発生日時,取引先,担当者,社員番号,カテゴリ,内容,対応工数(h),社員番号_y,名前,部署
0,4_10001,2022-04-17 16:35:07,テスト１株式会社,鈴木,1300000,契約内容,・・・,1.5,1300000,鈴木,第2営業部
1,4_10002,2022-04-25 16:53:39,テスト３株式会社,佐藤,1200000,契約内容,・・・,0.5,1200000,佐藤,第1営業部
2,4_10003,2022-04-09 16:04:13,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部
3,4_10004,2022-04-21 23:15:13,テスト１株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
4,4_10005,2022-04-08 12:59:55,テスト３株式会社,鈴木,1300000,その他,・・・,2.0,1300000,鈴木,第2営業部
5,4_10006,2022-04-15 17:11:47,テスト２株式会社,鈴木,1300000,契約内容,・・・,1.0,1300000,鈴木,第2営業部
6,4_10007,2022-04-13 00:57:33,テスト２株式会社,中村,1400000,契約内容,・・・,1.0,1400000,中村,第2営業部
7,4_10008,2022-04-17 00:15:48,テスト１株式会社,鈴木,1300000,使用方法,・・・,0.5,1300000,鈴木,第2営業部
8,4_10009,2022-04-08 15:02:22,テスト１株式会社,佐藤,1200000,その他,・・・,1.5,1200000,佐藤,第1営業部
9,4_10010,2022-04-21 07:45:41,テスト３株式会社,佐藤,1200000,契約内容,・・・,0.5,1200000,佐藤,第1営業部
10,4_10011,2022-04-29 20:29:25,テスト１株式会社,田中,1100000,使用方法,・・・,1.0,1100000,田中,第1営業部
11,4_10012,2022-04-30 06:22:19,テスト１株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
12,4_10013,2022-04-05 21:10:47,テスト３株式会社,佐藤,1200000,その他,・・・,1.0,1200000,佐藤,第1営業部
13,4_10014,2022-04-23 14:23:50,テスト１株式会社,田中,1100000,その他,・・・,1.5,1100000,田中,第1営業部
14,4_10015,2022-04-02 02:27:56,テスト１株式会社,鈴木,1300000,契約内容,・・・,2.0,1300000,鈴木,第2営業部
15,4_10016,2022-04-09 00:13:31,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部
16,4_10017,2022-04-08 23:27:21,テスト２株式会社,中村,1400000,契約内容,・・・,0.5,1400000,中村,第2営業部
17,4_10018,2022-04-28 15:54:55,テスト２株式会社,中村,1400000,その他,・・・,1.0,1400000,中村,第2営業部
18,4_10019,2022-04-24 11:48:17,テスト２株式会社,中村,1400000,契約内容,・・・,1.0,1400000,中村,第2営業部
19,4_10020,2022-04-10 13:45:33,テスト３株式会社,鈴木,1300000,その他,・・・,2.0,1300000,鈴木,第2営業部
20,4_10021,2022-04-19 20:00:11,テスト１株式会社,佐藤,1200000,使用方法,・・・,1.0,1200000,佐藤,第1営業部
21,4_10022,2022-04-03 07:12:07,テスト２株式会社,鈴木,1300000,使用方法,・・・,1.0,1300000,鈴木,第2営業部
22,4_10023,2022-04-14 21:33:52,テスト３株式会社,田中,1100000,使用方法,・・・,0.5,1100000,田中,第1営業部
23,4_10024,2022-04-22 15:38:34,テスト１株式会社,鈴木,1300000,使用方法,・・・,2.0,1300000,鈴木,第2営業部
24,4_10025,2022-04-02 13:34:11,テスト２株式会社,佐藤,1200000,契約内容,・・・,1.5,1200000,佐藤,第1営業部
25,4_10026,2022-04-21 08:28:44,テスト１株式会社,中村,1400000,契約内容,・・・,2.0,1400000,中村,第2営業部
26,4_10027,2022-04-26 07:48:02,テスト３株式会社,佐藤,1200000,使用方法,・・・,1.0,1200000,佐藤,第1営業部
27,4_10028,2022-04-29 07:43:31,テスト１株式会社,鈴木,1300000,契約内容,・・・,2.0,1300000,鈴木,第2営業部
28,4_10029,2022-04-23 14:37:18,テスト１株式会社,田中,1100000,契約内容,・・・,0.5,1100000,田中,第1営業部
29,4_10030,2022-04-02 23:13:24,テスト１株式会社,田中,1100000,使用方法,・・・,1.5,1100000,田中,第1営業部

# 差分検出

In [23]:
import pandas as pd

df_4=pd.read_csv("問い合わせ履歴_4月末時点.csv",encoding="shift-jis")
df_5=pd.read_csv("問い合わせ履歴_5月末時点.csv",encoding="shift-jis")
df_4
df_5

         ID             発生日時       取引先 担当者     社員番号  カテゴリ   内容  対応工数(h)
0   5_10001   2022/5/6 22:26  テスト２株式会社  鈴木  1300000  使用方法  ・・・      2.0
1   4_10018  2022/4/28 15:54  テスト２株式会社  中村  1400000   その他  ・・・      1.0
2   5_10004   2022/5/3 13:31  テスト２株式会社  田中  1100000  使用方法  ・・・      0.5
3   5_10009   2022/5/19 8:31  テスト３株式会社  佐藤  1200000  使用方法  ・・・      0.5
4   4_10026   2022/4/21 8:28  テスト１株式会社  中村  1400000  契約内容  ・・・      2.0
5   4_10028   2022/4/29 7:43  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
6   4_10007   2022/4/13 0:57  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
7   5_10005  2022/5/27 11:45  テスト２株式会社  中村  1400000  契約内容  ・・・      2.0
8   4_10022    2022/4/3 7:12  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.0
9   4_10034  2022/4/15 13:05  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.5
10  4_10001  2022/4/17 16:35  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.5
11  5_10006  2022/5/29 13:30  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
12  5_10013  2022/5/29 23:48  テスト１株式会社  中村  1400000  契約内容  ・・・      0.5
13  4_10027   2022/4/26 7:48  テスト３株式会社  佐藤  1200000  使用方法  ・・・      1.0
14  5_10014  2022/5/16 23:41  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.0
15  4_10004  2022/4/21 23:15  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
16  4_10021  2022/4/19 20:00  テスト１株式会社  佐藤  1200000  使用方法  ・・・      1.0
17  4_10030   2022/4/2 23:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
18  4_10011  2022/4/29 20:29  テスト１株式会社  田中  1100000  使用方法  ・・・      1.0
19  5_10007    2022/5/2 4:03  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.5
20  4_10013   2022/4/5 21:10  テスト３株式会社  佐藤  1200000   その他  ・・・      1.0
21  4_10012   2022/4/30 6:22  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
22  4_10002  2022/4/25 16:53  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
23  5_10015   2022/5/23 9:56  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
24  4_10035    2022/4/9 5:05  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
25  4_10019  2022/4/24 11:48  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
26  4_10015    2022/4/2 2:27  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
27  4_10023  2022/4/14 21:33  テスト３株式会社  田中  1100000  使用方法  ・・・      0.5
28  4_10024  2022/4/22 15:38  テスト１株式会社  鈴木  1300000  使用方法  ・・・      2.0
29  4_10006  2022/4/15 17:11  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0
30  4_10014  2022/4/23 14:23  テスト１株式会社  田中  1100000   その他  ・・・      1.5
31  5_10010  2022/5/14 12:33  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
32  4_10032  2022/4/19 14:05  テスト２株式会社  鈴木  1300000  使用方法  ・・・      0.5
33  4_10003   2022/4/9 16:04  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
34  5_10012   2022/5/21 5:18  テスト２株式会社  鈴木  1300000  契約内容  ・・・      0.5
35  4_10009   2022/4/8 15:02  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
36  4_10031   2022/4/25 3:58  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
37  5_10003  2022/5/25 10:45  テスト２株式会社  中村  1400000  契約内容  ・・・      2.0
38  4_10029  2022/4/23 14:37  テスト１株式会社  田中  1100000  契約内容  ・・・      0.5
39  4_10005   2022/4/8 12:59  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
40  4_10016    2022/4/9 0:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
41  4_10008   2022/4/17 0:15  テスト１株式会社  鈴木  1300000  使用方法  ・・・      0.5
42  4_10025   2022/4/2 13:34  テスト２株式会社  佐藤  1200000  契約内容  ・・・      1.5
43  5_10002    2022/5/4 3:24  テスト１株式会社  田中  1100000   その他  ・・・      1.0
44  4_10017   2022/4/8 23:27  テスト２株式会社  中村  1400000  契約内容  ・・・      0.5
45  4_10033    2022/4/5 3:15  テスト１株式会社  田中  1100000   その他  ・・・      1.0
46  5_10008   2022/5/7 11:43  テスト３株式会社  中村  1400000   その他  ・・・      0.5
47  5_10011   2022/5/25 8:17  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0

In [24]:
df_4

         ID                 発生日時       取引先 担当者     社員番号  カテゴリ   内容  対応工数(h)
0   4_10001  2022-04-17 16:35:07  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.5
1   4_10002  2022-04-25 16:53:39  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
2   4_10003  2022-04-09 16:04:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
3   4_10004  2022-04-21 23:15:13  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
4   4_10005  2022-04-08 12:59:55  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
5   4_10006  2022-04-15 17:11:47  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0
6   4_10007  2022-04-13 00:57:33  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
7   4_10008  2022-04-17 00:15:48  テスト１株式会社  鈴木  1300000  使用方法  ・・・      0.5
8   4_10009  2022-04-08 15:02:22  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
9   4_10010  2022-04-21 07:45:41  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
10  4_10011  2022-04-29 20:29:25  テスト１株式会社  田中  1100000  使用方法  ・・・      1.0
11  4_10012  2022-04-30 06:22:19  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
12  4_10013  2022-04-05 21:10:47  テスト３株式会社  佐藤  1200000   その他  ・・・      1.0
13  4_10014  2022-04-23 14:23:50  テスト１株式会社  田中  1100000   その他  ・・・      1.5
14  4_10015  2022-04-02 02:27:56  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
15  4_10016  2022-04-09 00:13:31  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
16  4_10017  2022-04-08 23:27:21  テスト２株式会社  中村  1400000  契約内容  ・・・      0.5
17  4_10018  2022-04-28 15:54:55  テスト２株式会社  中村  1400000   その他  ・・・      1.0
18  4_10019  2022-04-24 11:48:17  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
19  4_10020  2022-04-10 13:45:33  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
20  4_10021  2022-04-19 20:00:11  テスト１株式会社  佐藤  1200000  使用方法  ・・・      1.0
21  4_10022  2022-04-03 07:12:07  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.0
22  4_10023  2022-04-14 21:33:52  テスト３株式会社  田中  1100000  使用方法  ・・・      0.5
23  4_10024  2022-04-22 15:38:34  テスト１株式会社  鈴木  1300000  使用方法  ・・・      2.0
24  4_10025  2022-04-02 13:34:11  テスト２株式会社  佐藤  1200000  契約内容  ・・・      1.5
25  4_10026  2022-04-21 08:28:44  テスト１株式会社  中村  1400000  契約内容  ・・・      2.0
26  4_10027  2022-04-26 07:48:02  テスト３株式会社  佐藤  1200000  使用方法  ・・・      1.0
27  4_10028  2022-04-29 07:43:31  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
28  4_10029  2022-04-23 14:37:18  テスト１株式会社  田中  1100000  契約内容  ・・・      0.5
29  4_10030  2022-04-02 23:13:24  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5

In [25]:
df_5

         ID             発生日時       取引先 担当者     社員番号  カテゴリ   内容  対応工数(h)
0   5_10001   2022/5/6 22:26  テスト２株式会社  鈴木  1300000  使用方法  ・・・      2.0
1   4_10018  2022/4/28 15:54  テスト２株式会社  中村  1400000   その他  ・・・      1.0
2   5_10004   2022/5/3 13:31  テスト２株式会社  田中  1100000  使用方法  ・・・      0.5
3   5_10009   2022/5/19 8:31  テスト３株式会社  佐藤  1200000  使用方法  ・・・      0.5
4   4_10026   2022/4/21 8:28  テスト１株式会社  中村  1400000  契約内容  ・・・      2.0
5   4_10028   2022/4/29 7:43  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
6   4_10007   2022/4/13 0:57  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
7   5_10005  2022/5/27 11:45  テスト２株式会社  中村  1400000  契約内容  ・・・      2.0
8   4_10022    2022/4/3 7:12  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.0
9   4_10034  2022/4/15 13:05  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.5
10  4_10001  2022/4/17 16:35  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.5
11  5_10006  2022/5/29 13:30  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
12  5_10013  2022/5/29 23:48  テスト１株式会社  中村  1400000  契約内容  ・・・      0.5
13  4_10027   2022/4/26 7:48  テスト３株式会社  佐藤  1200000  使用方法  ・・・      1.0
14  5_10014  2022/5/16 23:41  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.0
15  4_10004  2022/4/21 23:15  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
16  4_10021  2022/4/19 20:00  テスト１株式会社  佐藤  1200000  使用方法  ・・・      1.0
17  4_10030   2022/4/2 23:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
18  4_10011  2022/4/29 20:29  テスト１株式会社  田中  1100000  使用方法  ・・・      1.0
19  5_10007    2022/5/2 4:03  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.5
20  4_10013   2022/4/5 21:10  テスト３株式会社  佐藤  1200000   その他  ・・・      1.0
21  4_10012   2022/4/30 6:22  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
22  4_10002  2022/4/25 16:53  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
23  5_10015   2022/5/23 9:56  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
24  4_10035    2022/4/9 5:05  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
25  4_10019  2022/4/24 11:48  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
26  4_10015    2022/4/2 2:27  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
27  4_10023  2022/4/14 21:33  テスト３株式会社  田中  1100000  使用方法  ・・・      0.5
28  4_10024  2022/4/22 15:38  テスト１株式会社  鈴木  1300000  使用方法  ・・・      2.0
29  4_10006  2022/4/15 17:11  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0
30  4_10014  2022/4/23 14:23  テスト１株式会社  田中  1100000   その他  ・・・      1.5
31  5_10010  2022/5/14 12:33  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
32  4_10032  2022/4/19 14:05  テスト２株式会社  鈴木  1300000  使用方法  ・・・      0.5
33  4_10003   2022/4/9 16:04  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
34  5_10012   2022/5/21 5:18  テスト２株式会社  鈴木  1300000  契約内容  ・・・      0.5
35  4_10009   2022/4/8 15:02  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
36  4_10031   2022/4/25 3:58  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
37  5_10003  2022/5/25 10:45  テスト２株式会社  中村  1400000  契約内容  ・・・      2.0
38  4_10029  2022/4/23 14:37  テスト１株式会社  田中  1100000  契約内容  ・・・      0.5
39  4_10005   2022/4/8 12:59  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
40  4_10016    2022/4/9 0:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
41  4_10008   2022/4/17 0:15  テスト１株式会社  鈴木  1300000  使用方法  ・・・      0.5
42  4_10025   2022/4/2 13:34  テスト２株式会社  佐藤  1200000  契約内容  ・・・      1.5
43  5_10002    2022/5/4 3:24  テスト１株式会社  田中  1100000   その他  ・・・      1.0
44  4_10017   2022/4/8 23:27  テスト２株式会社  中村  1400000  契約内容  ・・・      0.5
45  4_10033    2022/4/5 3:15  テスト１株式会社  田中  1100000   その他  ・・・      1.0
46  5_10008   2022/5/7 11:43  テスト３株式会社  中村  1400000   その他  ・・・      0.5
47  5_10011   2022/5/25 8:17  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0

In [32]:
df_merge=pd.merge(df_4,df_5,on="ID",how="outer",indicator=True)
df_merge

,ID,発生日時_x,取引先_x,担当者_x,社員番号_x,カテゴリ_x,内容_x,対応工数(h)_x,発生日時_y,取引先_y,担当者_y,社員番号_y,カテゴリ_y,内容_y,対応工数(h)_y,_merge
0,4_10001,2022-04-17 16:35:07,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,1.5,2022/4/17 16:35,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,1.5,both
1,4_10002,2022-04-25 16:53:39,テスト３株式会社,佐藤,1200000.0,契約内容,・・・,0.5,2022/4/25 16:53,テスト３株式会社,佐藤,1200000.0,契約内容,・・・,0.5,both
2,4_10003,2022-04-09 16:04:13,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,2022/4/9 16:04,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,both
3,4_10004,2022-04-21 23:15:13,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,2022/4/21 23:15,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,both
4,4_10005,2022-04-08 12:59:55,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,2022/4/8 12:59,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,both
5,4_10006,2022-04-15 17:11:47,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.0,2022/4/15 17:11,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.0,both
6,4_10007,2022-04-13 00:57:33,テスト２株式会社,中村,1400000.0,契約内容,・・・,1.0,2022/4/13 0:57,テスト２株式会社,中村,1400000.0,契約内容,・・・,1.0,both
7,4_10008,2022-04-17 00:15:48,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,0.5,2022/4/17 0:15,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,0.5,both
8,4_10009,2022-04-08 15:02:22,テスト１株式会社,佐藤,1200000.0,その他,・・・,1.5,2022/4/8 15:02,テスト１株式会社,佐藤,1200000.0,その他,・・・,1.5,both
9,4_10010,2022-04-21 07:45:41,テスト３株式会社,佐藤,1200000.0,契約内容,・・・,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,4_10011,2022-04-29 20:29:25,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.0,2022/4/29 20:29,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.0,both
11,4_10012,2022-04-30 06:22:19,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,2022/4/30 6:22,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,both
12,4_10013,2022-04-05 21:10:47,テスト３株式会社,佐藤,1200000.0,その他,・・・,1.0,2022/4/5 21:10,テスト３株式会社,佐藤,1200000.0,その他,・・・,1.0,both
13,4_10014,2022-04-23 14:23:50,テスト１株式会社,田中,1100000.0,その他,・・・,1.5,2022/4/23 14:23,テスト１株式会社,田中,1100000.0,その他,・・・,1.5,both
14,4_10015,2022-04-02 02:27:56,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,2.0,2022/4/2 2:27,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,2.0,both
15,4_10016,2022-04-09 00:13:31,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,2022/4/9 0:13,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,both
16,4_10017,2022-04-08 23:27:21,テスト２株式会社,中村,1400000.0,契約内容,・・・,0.5,2022/4/8 23:27,テスト２株式会社,中村,1400000.0,契約内容,・・・,0.5,both
17,4_10018,2022-04-28 15:54:55,テスト２株式会社,中村,1400000.0,その他,・・・,1.0,2022/4/28 15:54,テスト２株式会社,中村,1400000.0,その他,・・・,1.0,both
18,4_10019,2022-04-24 11:48:17,テスト２株式会社,中村,1400000.0,契約内容,・・・,1.0,2022/4/24 11:48,テスト２株式会社,中村,1400000.0,契約内容,・・・,1.0,both
19,4_10020,2022-04-10 13:45:33,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
20,4_10021,2022-04-19 20:00:11,テスト１株式会社,佐藤,1200000.0,使用方法,・・・,1.0,2022/4/19 20:00,テスト１株式会社,佐藤,1200000.0,使用方法,・・・,1.0,both
21,4_10022,2022-04-03 07:12:07,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,1.0,2022/4/3 7:12,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,1.0,both
22,4_10023,2022-04-14 21:33:52,テスト３株式会社,田中,1100000.0,使用方法,・・・,0.5,2022/4/14 21:33,テスト３株式会社,田中,1100000.0,使用方法,・・・,0.5,both
23,4_10024,2022-04-22 15:38:34,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,2.0,2022/4/22 15:38,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,2.0,both
24,4_10025,2022-04-02 13:34:11,テスト２株式会社,佐藤,1200000.0,契約内容,・・・,1.5,2022/4/2 13:34,テスト２株式会社,佐藤,1200000.0,契約内容,・・・,1.5,both
25,4_10026,2022-04-21 08:28:44,テスト１株式会社,中村,1400000.0,契約内容,・・・,2.0,2022/4/21 8:28,テスト１株式会社,中村,1400000.0,契約内容,・・・,2.0,both
26,4_10027,2022-04-26 07:48:02,テスト３株式会社,佐藤,1200000.0,使用方法,・・・,1.0,2022/4/26 7:48,テスト３株式会社,佐藤,1200000.0,使用方法,・・・,1.0,both
27,4_10028,2022-04-29 07:43:31,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,2.0,2022/4/29 7:43,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,2.0,both
28,4_10029,2022-04-23 14:37:18,テスト１株式会社,田中,1100000.0,契約内容,・・・,0.5,2022/4/23 14:37,テスト１株式会社,田中,1100000.0,契約内容,・・・,0.5,both
29,4_10030,2022-04-02 23:13:24,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,2022/4/2 23:13,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,both
30,4_10031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/25 3:58,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,right_only
31,4_10032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/19 14:05,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,0.5,right_only
32,4_10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/5 3:15,テスト１株式会社,田中,1100000.0,その他,・・・,1.0,right_only
33,4_10034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/15 13:05,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,1.5,right_only
34,4_10035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/9 5:05,テスト１株式会社,佐藤,1200000.0,その他,・・・,1.5,right_only
35,5_10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/6 22:26,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,2.0,right_only
36,5_10002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/4 3:24,テスト１株式会社,田中,1100000.0,その他,・・・,1.0,right_only
37,5_10003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/25 10:45,テスト２株式会社,中村,1400000.0,契約内容,・・・,2.0,right_only
38,5_10004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/3 13:31,テスト２株式会社,田中,1100000.0,使用方法,・・・,0.5,right_only
39,5_10005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/27 11:45,テスト２株式会社,中村,1400000.0,契約内容,・・・,2.0,right_only
40,5_10006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/29 13:30,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,right_only
41,5_10007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/2 4:03,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.5,right_only
42,5_10008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/7 11:43,テスト３株式会社,中村,1400000.0,その他,・・・,0.5,right_only
43,5_10009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/19 8:31,テスト３株式会社,佐藤,1200000.0,使用方法,・・・,0.5,right_only
44,5_10010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/14 12:33,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,right_only
45,5_10011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/25 8:17,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.0,right_only
46,5_10012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/21 5:18,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,0.5,right_only
47,5_10013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/29 23:48,テスト１株式会社,中村,1400000.0,契約内容,・・・,0.5,right_only
48,5_10014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/16 23:41,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,1.0,right_only
49,5_10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/23 9:56,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,right_only

In [35]:
df_merge[df_merge["_merge"]=="right_only"]

,ID,発生日時_x,取引先_x,担当者_x,社員番号_x,カテゴリ_x,内容_x,対応工数(h)_x,発生日時_y,取引先_y,担当者_y,社員番号_y,カテゴリ_y,内容_y,対応工数(h)_y,_merge
30,4_10031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/25 3:58,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,right_only
31,4_10032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/19 14:05,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,0.5,right_only
32,4_10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/5 3:15,テスト１株式会社,田中,1100000.0,その他,・・・,1.0,right_only
33,4_10034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/15 13:05,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,1.5,right_only
34,4_10035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/4/9 5:05,テスト１株式会社,佐藤,1200000.0,その他,・・・,1.5,right_only
35,5_10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/6 22:26,テスト２株式会社,鈴木,1300000.0,使用方法,・・・,2.0,right_only
36,5_10002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/4 3:24,テスト１株式会社,田中,1100000.0,その他,・・・,1.0,right_only
37,5_10003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/25 10:45,テスト２株式会社,中村,1400000.0,契約内容,・・・,2.0,right_only
38,5_10004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/3 13:31,テスト２株式会社,田中,1100000.0,使用方法,・・・,0.5,right_only
39,5_10005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/27 11:45,テスト２株式会社,中村,1400000.0,契約内容,・・・,2.0,right_only
40,5_10006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/29 13:30,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,right_only
41,5_10007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/2 4:03,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.5,right_only
42,5_10008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/7 11:43,テスト３株式会社,中村,1400000.0,その他,・・・,0.5,right_only
43,5_10009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/19 8:31,テスト３株式会社,佐藤,1200000.0,使用方法,・・・,0.5,right_only
44,5_10010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/14 12:33,テスト１株式会社,鈴木,1300000.0,使用方法,・・・,1.0,right_only
45,5_10011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/25 8:17,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,1.0,right_only
46,5_10012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/21 5:18,テスト２株式会社,鈴木,1300000.0,契約内容,・・・,0.5,right_only
47,5_10013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/29 23:48,テスト１株式会社,中村,1400000.0,契約内容,・・・,0.5,right_only
48,5_10014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/16 23:41,テスト１株式会社,鈴木,1300000.0,契約内容,・・・,1.0,right_only
49,5_10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022/5/23 9:56,テスト１株式会社,田中,1100000.0,使用方法,・・・,1.5,right_only

In [36]:
df_merge[df_merge["_merge"]=="left_only"]

,ID,発生日時_x,取引先_x,担当者_x,社員番号_x,カテゴリ_x,内容_x,対応工数(h)_x,発生日時_y,取引先_y,担当者_y,社員番号_y,カテゴリ_y,内容_y,対応工数(h)_y,_merge
9,4_10010,2022-04-21 07:45:41,テスト３株式会社,佐藤,1200000.0,契約内容,・・・,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
19,4_10020,2022-04-10 13:45:33,テスト３株式会社,鈴木,1300000.0,その他,・・・,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

# ピボットテーブル

In [37]:
import pandas as pd

df=pd.read_csv("問い合わせ履歴_4月末時点.csv",encoding="shift-jis")
df

         ID                 発生日時       取引先 担当者     社員番号  カテゴリ   内容  対応工数(h)
0   4_10001  2022-04-17 16:35:07  テスト１株式会社  鈴木  1300000  契約内容  ・・・      1.5
1   4_10002  2022-04-25 16:53:39  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
2   4_10003  2022-04-09 16:04:13  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
3   4_10004  2022-04-21 23:15:13  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
4   4_10005  2022-04-08 12:59:55  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
5   4_10006  2022-04-15 17:11:47  テスト２株式会社  鈴木  1300000  契約内容  ・・・      1.0
6   4_10007  2022-04-13 00:57:33  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
7   4_10008  2022-04-17 00:15:48  テスト１株式会社  鈴木  1300000  使用方法  ・・・      0.5
8   4_10009  2022-04-08 15:02:22  テスト１株式会社  佐藤  1200000   その他  ・・・      1.5
9   4_10010  2022-04-21 07:45:41  テスト３株式会社  佐藤  1200000  契約内容  ・・・      0.5
10  4_10011  2022-04-29 20:29:25  テスト１株式会社  田中  1100000  使用方法  ・・・      1.0
11  4_10012  2022-04-30 06:22:19  テスト１株式会社  鈴木  1300000  使用方法  ・・・      1.0
12  4_10013  2022-04-05 21:10:47  テスト３株式会社  佐藤  1200000   その他  ・・・      1.0
13  4_10014  2022-04-23 14:23:50  テスト１株式会社  田中  1100000   その他  ・・・      1.5
14  4_10015  2022-04-02 02:27:56  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
15  4_10016  2022-04-09 00:13:31  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5
16  4_10017  2022-04-08 23:27:21  テスト２株式会社  中村  1400000  契約内容  ・・・      0.5
17  4_10018  2022-04-28 15:54:55  テスト２株式会社  中村  1400000   その他  ・・・      1.0
18  4_10019  2022-04-24 11:48:17  テスト２株式会社  中村  1400000  契約内容  ・・・      1.0
19  4_10020  2022-04-10 13:45:33  テスト３株式会社  鈴木  1300000   その他  ・・・      2.0
20  4_10021  2022-04-19 20:00:11  テスト１株式会社  佐藤  1200000  使用方法  ・・・      1.0
21  4_10022  2022-04-03 07:12:07  テスト２株式会社  鈴木  1300000  使用方法  ・・・      1.0
22  4_10023  2022-04-14 21:33:52  テスト３株式会社  田中  1100000  使用方法  ・・・      0.5
23  4_10024  2022-04-22 15:38:34  テスト１株式会社  鈴木  1300000  使用方法  ・・・      2.0
24  4_10025  2022-04-02 13:34:11  テスト２株式会社  佐藤  1200000  契約内容  ・・・      1.5
25  4_10026  2022-04-21 08:28:44  テスト１株式会社  中村  1400000  契約内容  ・・・      2.0
26  4_10027  2022-04-26 07:48:02  テスト３株式会社  佐藤  1200000  使用方法  ・・・      1.0
27  4_10028  2022-04-29 07:43:31  テスト１株式会社  鈴木  1300000  契約内容  ・・・      2.0
28  4_10029  2022-04-23 14:37:18  テスト１株式会社  田中  1100000  契約内容  ・・・      0.5
29  4_10030  2022-04-02 23:13:24  テスト１株式会社  田中  1100000  使用方法  ・・・      1.5

In [38]:
df.pivot_table(index="担当者",columns="取引先",values="対応工数(h)",aggfunc="sum")

取引先  テスト１株式会社  テスト２株式会社  テスト３株式会社
担当者
中村        2.0       3.5       NaN
佐藤        2.5       1.5       3.0
田中        7.5       NaN       0.5
鈴木       10.0       2.0       4.0

In [40]:
df.pivot_table(index="担当者",columns=["取引先","カテゴリ"],values="対応工数(h)",aggfunc="sum",fill_value=0)

取引先  テスト１株式会社           テスト２株式会社           テスト３株式会社
カテゴリ      その他 使用方法 契約内容      その他 使用方法 契約内容      その他 使用方法 契約内容
担当者
中村        0.0  0.0  2.0      1.0  0.0  2.5      0.0  0.0  0.0
佐藤        1.5  1.0  0.0      0.0  0.0  1.5      1.0  1.0  1.0
田中        1.5  5.5  0.5      0.0  0.0  0.0      0.0  0.5  0.0
鈴木        0.0  4.5  5.5      0.0  1.0  1.0      4.0  0.0  0.0

In [46]:
df6=df.pivot_table(index="担当者",columns=["取引先","カテゴリ"],values="対応工数(h)",aggfunc="sum",fill_value=0)
df6

取引先  テスト１株式会社           テスト２株式会社           テスト３株式会社
カテゴリ      その他 使用方法 契約内容      その他 使用方法 契約内容      その他 使用方法 契約内容
担当者
中村        0.0  0.0  2.0      1.0  0.0  2.5      0.0  0.0  0.0
佐藤        1.5  1.0  0.0      0.0  0.0  1.5      1.0  1.0  1.0
田中        1.5  5.5  0.5      0.0  0.0  0.0      0.0  0.5  0.0
鈴木        0.0  4.5  5.5      0.0  1.0  1.0      4.0  0.0  0.0

In [47]:
df6.to_excel("担当者カテゴリ別.xlsx")