In [1]:
import pandas as pd

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\salzburug\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\salzburug\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
df=pd.read_excel("売上一覧.xlsx",sheet_name="Sheet1")
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  中村  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df["売上金額"]

0       6000
1      50000
2     200000
3      12000
4     200000
       ...
95     12000
96    500000
97     30000
98      3000
99    300000
Name: 売上金額, Length: 100, dtype: int64

In [7]:
type(df["売上金額"])

pandas.core.series.Series

In [8]:
df["売上金額"].sum()

np.int64(13697000)

In [9]:
df["売上金額"].mean()

np.float64(136970.0)

In [10]:
df["売上金額"].count()

np.int64(100)

In [12]:
df[["担当者","売上金額"]]

   担当者    売上金額
0   田中    6000
1   佐藤   50000
2   中村  200000
3   鈴木   12000
4   田中  200000
..  ..     ...
95  佐藤   12000
96  佐藤  500000
97  鈴木   30000
98  佐藤    3000
99  佐藤  300000

[100 rows x 2 columns]

In [13]:
df.iloc[2,3]

'中村'

In [14]:
df.iloc[2,3]="大内"

In [15]:
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  大内  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [16]:
df.iloc[1:4,0:3]

   No.        取引日       取引先
1    2 2022-04-02  テスト２株式会社
2    3 2022-04-03  テスト２株式会社
3    4 2022-04-04  テスト３株式会社

In [17]:
df.iloc[1:4,[0,2]]

   No.       取引先
1    2  テスト２株式会社
2    3  テスト２株式会社
3    4  テスト３株式会社

In [18]:
df.iloc[1:4,:]

   No.        取引日       取引先 担当者    商品名     単価  個数    売上金額
1    2 2022-04-02  テスト２株式会社  佐藤  タブレット  50000   1   50000
2    3 2022-04-03  テスト２株式会社  大内  タブレット  50000   4  200000
3    4 2022-04-04  テスト３株式会社  鈴木  キーボード   6000   2   12000

In [19]:
df.iloc[:,0:3]

    No.        取引日       取引先
0     1 2022-04-01  テスト１株式会社
1     2 2022-04-02  テスト２株式会社
2     3 2022-04-03  テスト２株式会社
3     4 2022-04-04  テスト３株式会社
4     5 2022-04-05  テスト１株式会社
..  ...        ...       ...
95   96 2022-07-05  テスト１株式会社
96   97 2022-07-06  テスト１株式会社
97   98 2022-07-07  テスト３株式会社
98   99 2022-07-08  テスト２株式会社
99  100 2022-07-09  テスト１株式会社

[100 rows x 3 columns]

In [20]:
df.iloc[:,[3,7]]

   担当者    売上金額
0   田中    6000
1   佐藤   50000
2   大内  200000
3   鈴木   12000
4   田中  200000
..  ..     ...
95  佐藤   12000
96  佐藤  500000
97  鈴木   30000
98  佐藤    3000
99  佐藤  300000

[100 rows x 2 columns]

In [21]:
df["商品名"].str.replace("PC","パソコン")

0     キーボード
1     タブレット
2     タブレット
3     キーボード
4     タブレット
      ...
95    キーボード
96     パソコン
97    キーボード
98      マウス
99     パソコン
Name: 商品名, Length: 100, dtype: object

In [22]:
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  大内  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [23]:
df["商品名"]=df["商品名"].str.replace("PC","パソコン")

In [24]:
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  大内  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]

In [25]:
df["商品名"]=df["商品名"].str.replace("ボード","ぼーど")
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーぼーど    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  大内  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーぼーど    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーぼーど    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーぼーど    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]

In [27]:
df["商品名"]=df["商品名"].str.replace("レット","")
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーぼーど    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤     タブ   50000   1   50000
2     3 2022-04-03  テスト２株式会社  大内     タブ   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーぼーど    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中     タブ   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーぼーど    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤   パソコン  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーぼーど    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤   パソコン  100000   3  300000

[100 rows x 8 columns]

In [28]:
# ファイルの分割

# ファイルの分割

In [29]:
import pandas as pd
df=pd.read_excel("売上一覧.xlsx",sheet_name="Sheet1")
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  中村  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [31]:
df[df["担当者"]=="田中"]

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
7     8 2022-04-08  テスト１株式会社  田中  タブレット   50000   2  100000
8     9 2022-04-09  テスト１株式会社  田中  タブレット   50000   2  100000
11   12 2022-04-12  テスト１株式会社  田中     PC  100000   2  200000
14   15 2022-04-15  テスト１株式会社  田中  タブレット   50000   5  250000
16   17 2022-04-17  テスト２株式会社  田中     PC  100000   1  100000
17   18 2022-04-18  テスト２株式会社  田中     PC  100000   4  400000
22   23 2022-04-23  テスト２株式会社  田中    マウス    1500   2    3000
23   24 2022-04-24  テスト１株式会社  田中     PC  100000   4  400000
25   26 2022-04-26  テスト２株式会社  田中  キーボード    6000   3   18000
37   38 2022-05-08  テスト１株式会社  田中  タブレット   50000   1   50000
42   43 2022-05-13  テスト１株式会社  田中  キーボード    6000   3   18000
43   44 2022-05-14  テスト１株式会社  田中  タブレット   50000   2  100000
44   45 2022-05-15  テスト２株式会社  田中  タブレット   50000   5  250000
45   46 2022-05-16  テスト２株式会社  田中  タブレット   50000   5  250000
46   47 2022-05-17  テスト２株式会社  田中    マウス    1500   4    6000
53   54 2022-05-24  テスト１株式会社  田中    マウス    1500   5    7500
57   58 2022-05-28  テスト２株式会社  田中  タブレット   50000   4  200000
71   72 2022-06-11  テスト１株式会社  田中  キーボード    6000   4   24000
76   77 2022-06-16  テスト１株式会社  田中  タブレット   50000   3  150000
79   80 2022-06-19  テスト２株式会社  田中    マウス    1500   1    1500
80   81 2022-06-20  テスト１株式会社  田中     PC  100000   4  400000
85   86 2022-06-25  テスト１株式会社  田中    マウス    1500   4    6000
87   88 2022-06-27  テスト２株式会社  田中  キーボード    6000   3   18000

In [32]:
df["担当者"]=="田中"

0      True
1     False
2     False
3     False
4      True
      ...
95    False
96    False
97    False
98    False
99    False
Name: 担当者, Length: 100, dtype: bool

In [33]:
df[df["売上金額"]>=300000]

    No.        取引日       取引先 担当者 商品名      単価  個数    売上金額
6     7 2022-04-07  テスト１株式会社  佐藤  PC  100000   4  400000
9    10 2022-04-10  テスト２株式会社  中村  PC  100000   4  400000
15   16 2022-04-16  テスト１株式会社  佐藤  PC  100000   5  500000
17   18 2022-04-18  テスト２株式会社  田中  PC  100000   4  400000
23   24 2022-04-24  テスト１株式会社  田中  PC  100000   4  400000
26   27 2022-04-27  テスト１株式会社  鈴木  PC  100000   4  400000
35   36 2022-05-06  テスト１株式会社  佐藤  PC  100000   5  500000
49   50 2022-05-20  テスト３株式会社  鈴木  PC  100000   5  500000
54   55 2022-05-25  テスト１株式会社  鈴木  PC  100000   3  300000
56   57 2022-05-27  テスト３株式会社  鈴木  PC  100000   4  400000
64   65 2022-06-04  テスト３株式会社  鈴木  PC  100000   4  400000
65   66 2022-06-05  テスト３株式会社  鈴木  PC  100000   3  300000
67   68 2022-06-07  テスト１株式会社  佐藤  PC  100000   5  500000
74   75 2022-06-14  テスト１株式会社  佐藤  PC  100000   4  400000
80   81 2022-06-20  テスト１株式会社  田中  PC  100000   4  400000
91   92 2022-07-01  テスト１株式会社  佐藤  PC  100000   4  400000
92   93 2022-07-02  テスト２株式会社  中村  PC  100000   4  400000
96   97 2022-07-06  テスト１株式会社  佐藤  PC  100000   5  500000
99  100 2022-07-09  テスト１株式会社  佐藤  PC  100000   3  300000

In [34]:
df[(df["担当者"]=="田中")&(df["売上金額"]>=300000)]

    No.        取引日       取引先 担当者 商品名      単価  個数    売上金額
17   18 2022-04-18  テスト２株式会社  田中  PC  100000   4  400000
23   24 2022-04-24  テスト１株式会社  田中  PC  100000   4  400000
80   81 2022-06-20  テスト１株式会社  田中  PC  100000   4  400000

In [35]:
df[(df["担当者"]=="田中")|(df["売上金額"]>=300000)]

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
6     7 2022-04-07  テスト１株式会社  佐藤     PC  100000   4  400000
7     8 2022-04-08  テスト１株式会社  田中  タブレット   50000   2  100000
8     9 2022-04-09  テスト１株式会社  田中  タブレット   50000   2  100000
9    10 2022-04-10  テスト２株式会社  中村     PC  100000   4  400000
11   12 2022-04-12  テスト１株式会社  田中     PC  100000   2  200000
14   15 2022-04-15  テスト１株式会社  田中  タブレット   50000   5  250000
15   16 2022-04-16  テスト１株式会社  佐藤     PC  100000   5  500000
16   17 2022-04-17  テスト２株式会社  田中     PC  100000   1  100000
17   18 2022-04-18  テスト２株式会社  田中     PC  100000   4  400000
22   23 2022-04-23  テスト２株式会社  田中    マウス    1500   2    3000
23   24 2022-04-24  テスト１株式会社  田中     PC  100000   4  400000
25   26 2022-04-26  テスト２株式会社  田中  キーボード    6000   3   18000
26   27 2022-04-27  テスト１株式会社  鈴木     PC  100000   4  400000
35   36 2022-05-06  テスト１株式会社  佐藤     PC  100000   5  500000
37   38 2022-05-08  テスト１株式会社  田中  タブレット   50000   1   50000
42   43 2022-05-13  テスト１株式会社  田中  キーボード    6000   3   18000
43   44 2022-05-14  テスト１株式会社  田中  タブレット   50000   2  100000
44   45 2022-05-15  テスト２株式会社  田中  タブレット   50000   5  250000
45   46 2022-05-16  テスト２株式会社  田中  タブレット   50000   5  250000
46   47 2022-05-17  テスト２株式会社  田中    マウス    1500   4    6000
49   50 2022-05-20  テスト３株式会社  鈴木     PC  100000   5  500000
53   54 2022-05-24  テスト１株式会社  田中    マウス    1500   5    7500
54   55 2022-05-25  テスト１株式会社  鈴木     PC  100000   3  300000
56   57 2022-05-27  テスト３株式会社  鈴木     PC  100000   4  400000
57   58 2022-05-28  テスト２株式会社  田中  タブレット   50000   4  200000
64   65 2022-06-04  テスト３株式会社  鈴木     PC  100000   4  400000
65   66 2022-06-05  テスト３株式会社  鈴木     PC  100000   3  300000
67   68 2022-06-07  テスト１株式会社  佐藤     PC  100000   5  500000
71   72 2022-06-11  テスト１株式会社  田中  キーボード    6000   4   24000
74   75 2022-06-14  テスト１株式会社  佐藤     PC  100000   4  400000
76   77 2022-06-16  テスト１株式会社  田中  タブレット   50000   3  150000
79   80 2022-06-19  テスト２株式会社  田中    マウス    1500   1    1500
80   81 2022-06-20  テスト１株式会社  田中     PC  100000   4  400000
85   86 2022-06-25  テスト１株式会社  田中    マウス    1500   4    6000
87   88 2022-06-27  テスト２株式会社  田中  キーボード    6000   3   18000
91   92 2022-07-01  テスト１株式会社  佐藤     PC  100000   4  400000
92   93 2022-07-02  テスト２株式会社  中村     PC  100000   4  400000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

In [37]:
df[(df["担当者"]=="田中")|(df["売上金額"]>=300000)].iloc[99,3]

IndexError: index 99 is out of bounds for axis 0 with size 41

In [38]:
df[(df["担当者"]=="田中")|(df["売上金額"]>=300000)].reset_index(drop=True)

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
2     7 2022-04-07  テスト１株式会社  佐藤     PC  100000   4  400000
3     8 2022-04-08  テスト１株式会社  田中  タブレット   50000   2  100000
4     9 2022-04-09  テスト１株式会社  田中  タブレット   50000   2  100000
5    10 2022-04-10  テスト２株式会社  中村     PC  100000   4  400000
6    12 2022-04-12  テスト１株式会社  田中     PC  100000   2  200000
7    15 2022-04-15  テスト１株式会社  田中  タブレット   50000   5  250000
8    16 2022-04-16  テスト１株式会社  佐藤     PC  100000   5  500000
9    17 2022-04-17  テスト２株式会社  田中     PC  100000   1  100000
10   18 2022-04-18  テスト２株式会社  田中     PC  100000   4  400000
11   23 2022-04-23  テスト２株式会社  田中    マウス    1500   2    3000
12   24 2022-04-24  テスト１株式会社  田中     PC  100000   4  400000
13   26 2022-04-26  テスト２株式会社  田中  キーボード    6000   3   18000
14   27 2022-04-27  テスト１株式会社  鈴木     PC  100000   4  400000
15   36 2022-05-06  テスト１株式会社  佐藤     PC  100000   5  500000
16   38 2022-05-08  テスト１株式会社  田中  タブレット   50000   1   50000
17   43 2022-05-13  テスト１株式会社  田中  キーボード    6000   3   18000
18   44 2022-05-14  テスト１株式会社  田中  タブレット   50000   2  100000
19   45 2022-05-15  テスト２株式会社  田中  タブレット   50000   5  250000
20   46 2022-05-16  テスト２株式会社  田中  タブレット   50000   5  250000
21   47 2022-05-17  テスト２株式会社  田中    マウス    1500   4    6000
22   50 2022-05-20  テスト３株式会社  鈴木     PC  100000   5  500000
23   54 2022-05-24  テスト１株式会社  田中    マウス    1500   5    7500
24   55 2022-05-25  テスト１株式会社  鈴木     PC  100000   3  300000
25   57 2022-05-27  テスト３株式会社  鈴木     PC  100000   4  400000
26   58 2022-05-28  テスト２株式会社  田中  タブレット   50000   4  200000
27   65 2022-06-04  テスト３株式会社  鈴木     PC  100000   4  400000
28   66 2022-06-05  テスト３株式会社  鈴木     PC  100000   3  300000
29   68 2022-06-07  テスト１株式会社  佐藤     PC  100000   5  500000
30   72 2022-06-11  テスト１株式会社  田中  キーボード    6000   4   24000
31   75 2022-06-14  テスト１株式会社  佐藤     PC  100000   4  400000
32   77 2022-06-16  テスト１株式会社  田中  タブレット   50000   3  150000
33   80 2022-06-19  テスト２株式会社  田中    マウス    1500   1    1500
34   81 2022-06-20  テスト１株式会社  田中     PC  100000   4  400000
35   86 2022-06-25  テスト１株式会社  田中    マウス    1500   4    6000
36   88 2022-06-27  テスト２株式会社  田中  キーボード    6000   3   18000
37   92 2022-07-01  テスト１株式会社  佐藤     PC  100000   4  400000
38   93 2022-07-02  テスト２株式会社  中村     PC  100000   4  400000
39   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
40  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

In [39]:
df

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
2     3 2022-04-03  テスト２株式会社  中村  タブレット   50000   4  200000
3     4 2022-04-04  テスト３株式会社  鈴木  キーボード    6000   2   12000
4     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
..  ...        ...       ...  ..    ...     ...  ..     ...
95   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
96   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
97   98 2022-07-07  テスト３株式会社  鈴木  キーボード    6000   5   30000
98   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
99  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

[100 rows x 8 columns]

In [43]:
df2=df[(df["担当者"]=="田中")|(df["売上金額"]>=300000)].reset_index(drop=True)
df2

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     1 2022-04-01  テスト１株式会社  田中  キーボード    6000   1    6000
1     5 2022-04-05  テスト１株式会社  田中  タブレット   50000   4  200000
2     7 2022-04-07  テスト１株式会社  佐藤     PC  100000   4  400000
3     8 2022-04-08  テスト１株式会社  田中  タブレット   50000   2  100000
4     9 2022-04-09  テスト１株式会社  田中  タブレット   50000   2  100000
5    10 2022-04-10  テスト２株式会社  中村     PC  100000   4  400000
6    12 2022-04-12  テスト１株式会社  田中     PC  100000   2  200000
7    15 2022-04-15  テスト１株式会社  田中  タブレット   50000   5  250000
8    16 2022-04-16  テスト１株式会社  佐藤     PC  100000   5  500000
9    17 2022-04-17  テスト２株式会社  田中     PC  100000   1  100000
10   18 2022-04-18  テスト２株式会社  田中     PC  100000   4  400000
11   23 2022-04-23  テスト２株式会社  田中    マウス    1500   2    3000
12   24 2022-04-24  テスト１株式会社  田中     PC  100000   4  400000
13   26 2022-04-26  テスト２株式会社  田中  キーボード    6000   3   18000
14   27 2022-04-27  テスト１株式会社  鈴木     PC  100000   4  400000
15   36 2022-05-06  テスト１株式会社  佐藤     PC  100000   5  500000
16   38 2022-05-08  テスト１株式会社  田中  タブレット   50000   1   50000
17   43 2022-05-13  テスト１株式会社  田中  キーボード    6000   3   18000
18   44 2022-05-14  テスト１株式会社  田中  タブレット   50000   2  100000
19   45 2022-05-15  テスト２株式会社  田中  タブレット   50000   5  250000
20   46 2022-05-16  テスト２株式会社  田中  タブレット   50000   5  250000
21   47 2022-05-17  テスト２株式会社  田中    マウス    1500   4    6000
22   50 2022-05-20  テスト３株式会社  鈴木     PC  100000   5  500000
23   54 2022-05-24  テスト１株式会社  田中    マウス    1500   5    7500
24   55 2022-05-25  テスト１株式会社  鈴木     PC  100000   3  300000
25   57 2022-05-27  テスト３株式会社  鈴木     PC  100000   4  400000
26   58 2022-05-28  テスト２株式会社  田中  タブレット   50000   4  200000
27   65 2022-06-04  テスト３株式会社  鈴木     PC  100000   4  400000
28   66 2022-06-05  テスト３株式会社  鈴木     PC  100000   3  300000
29   68 2022-06-07  テスト１株式会社  佐藤     PC  100000   5  500000
30   72 2022-06-11  テスト１株式会社  田中  キーボード    6000   4   24000
31   75 2022-06-14  テスト１株式会社  佐藤     PC  100000   4  400000
32   77 2022-06-16  テスト１株式会社  田中  タブレット   50000   3  150000
33   80 2022-06-19  テスト２株式会社  田中    マウス    1500   1    1500
34   81 2022-06-20  テスト１株式会社  田中     PC  100000   4  400000
35   86 2022-06-25  テスト１株式会社  田中    マウス    1500   4    6000
36   88 2022-06-27  テスト２株式会社  田中  キーボード    6000   3   18000
37   92 2022-07-01  テスト１株式会社  佐藤     PC  100000   4  400000
38   93 2022-07-02  テスト２株式会社  中村     PC  100000   4  400000
39   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
40  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

In [44]:
df2["売上金額"].sum()

np.int64(9858000)

In [48]:
import pandas as pd
df=pd.read_excel("売上一覧.xlsx",sheet_name="Sheet1")
df_tanaka=df[df["担当者"]=="田中"]
df_tanaka.to_excel("売上一覧_田中.xlsx",index=False)

In [51]:
# 完成版
import pandas as pd
df=pd.read_excel("売上一覧.xlsx",sheet_name="Sheet1")

tantou_list=["田中","佐藤","鈴木","中村"]
df["担当者"].unique()

for tantou in tantou_list:
    df_tantou=df[df["担当者"]==tantou]
    df_tantou.to_excel("売上一覧_{}.xlsx".format(tantou),index=False)

In [52]:
df["担当者"].unique()

array(['田中', '佐藤', '中村', '鈴木'], dtype=object)

In [53]:
type(df["担当者"].unique())

numpy.ndarray

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\salzburug\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\salzburug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\salzburug\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

# ファイルの結合

In [3]:
from glob import glob
files=glob("売上一覧_*.xlsx")
files

['売上一覧_中村.xlsx', '売上一覧_佐藤.xlsx', '売上一覧_田中.xlsx', '売上一覧_鈴木.xlsx']

In [4]:
import pandas as pd

df_tanaka=pd.read_excel(files[0],sheet_name="Sheet1")
df_satou=pd.read_excel(files[1],sheet_name="Sheet1")

df_concat=pd.concat([df_tanaka,df_satou])
df_concat

    No.        取引日       取引先 担当者    商品名      単価  個数    売上金額
0     3 2022-04-03  テスト２株式会社  中村  タブレット   50000   4  200000
1    10 2022-04-10  テスト２株式会社  中村     PC  100000   4  400000
2    14 2022-04-14  テスト１株式会社  中村  タブレット   50000   3  150000
3    19 2022-04-19  テスト１株式会社  中村  キーボード    6000   5   30000
4    21 2022-04-21  テスト３株式会社  中村    マウス    1500   2    3000
5    39 2022-05-09  テスト３株式会社  中村  タブレット   50000   4  200000
6    51 2022-05-21  テスト２株式会社  中村    マウス    1500   2    3000
7    52 2022-05-22  テスト２株式会社  中村  タブレット   50000   2  100000
8    62 2022-06-01  テスト３株式会社  中村  キーボード    6000   3   18000
9    69 2022-06-08  テスト１株式会社  中村    マウス    1500   4    6000
10   71 2022-06-10  テスト１株式会社  中村  タブレット   50000   4  200000
11   83 2022-06-22  テスト３株式会社  中村  タブレット   50000   3  150000
12   84 2022-06-23  テスト１株式会社  中村    マウス    1500   1    1500
13   87 2022-06-26  テスト３株式会社  中村  キーボード    6000   2   12000
14   93 2022-07-02  テスト２株式会社  中村     PC  100000   4  400000
15   94 2022-07-03  テスト１株式会社  中村  キーボード    6000   3   18000
0     2 2022-04-02  テスト２株式会社  佐藤  タブレット   50000   1   50000
1     7 2022-04-07  テスト１株式会社  佐藤     PC  100000   4  400000
2    11 2022-04-11  テスト２株式会社  佐藤    マウス    1500   5    7500
3    16 2022-04-16  テスト１株式会社  佐藤     PC  100000   5  500000
4    20 2022-04-20  テスト２株式会社  佐藤  タブレット   50000   4  200000
5    22 2022-04-22  テスト１株式会社  佐藤  キーボード    6000   3   18000
6    28 2022-04-28  テスト１株式会社  佐藤     PC  100000   2  200000
7    29 2022-04-29  テスト１株式会社  佐藤     PC  100000   2  200000
8    30 2022-04-30  テスト３株式会社  佐藤    マウス    1500   2    3000
9    32 2022-05-02  テスト１株式会社  佐藤  タブレット   50000   1   50000
10   33 2022-05-03  テスト１株式会社  佐藤    マウス    1500   2    3000
11   34 2022-05-04  テスト１株式会社  佐藤    マウス    1500   2    3000
12   36 2022-05-06  テスト１株式会社  佐藤     PC  100000   5  500000
13   37 2022-05-07  テスト１株式会社  佐藤  キーボード    6000   1    6000
14   40 2022-05-10  テスト１株式会社  佐藤  タブレット   50000   2  100000
15   48 2022-05-18  テスト１株式会社  佐藤     PC  100000   2  200000
16   49 2022-05-19  テスト２株式会社  佐藤     PC  100000   1  100000
17   59 2022-05-29  テスト１株式会社  佐藤  タブレット   50000   3  150000
18   60 2022-05-30  テスト１株式会社  佐藤  タブレット   50000   5  250000
19   64 2022-06-03  テスト１株式会社  佐藤    マウス    1500   5    7500
20   67 2022-06-06  テスト１株式会社  佐藤  キーボード    6000   5   30000
21   68 2022-06-07  テスト１株式会社  佐藤     PC  100000   5  500000
22   73 2022-06-12  テスト１株式会社  佐藤  タブレット   50000   3  150000
23   74 2022-06-13  テスト１株式会社  佐藤  キーボード    6000   1    6000
24   75 2022-06-14  テスト１株式会社  佐藤     PC  100000   4  400000
25   76 2022-06-15  テスト３株式会社  佐藤  タブレット   50000   4  200000
26   78 2022-06-17  テスト２株式会社  佐藤    マウス    1500   5    7500
27   85 2022-06-24  テスト１株式会社  佐藤  キーボード    6000   2   12000
28   89 2022-06-28  テスト２株式会社  佐藤  キーボード    6000   4   24000
29   90 2022-06-29  テスト１株式会社  佐藤  キーボード    6000   3   18000
30   91 2022-06-30  テスト１株式会社  佐藤  タブレット   50000   1   50000
31   92 2022-07-01  テスト１株式会社  佐藤     PC  100000   4  400000
32   96 2022-07-05  テスト１株式会社  佐藤  キーボード    6000   2   12000
33   97 2022-07-06  テスト１株式会社  佐藤     PC  100000   5  500000
34   99 2022-07-08  テスト２株式会社  佐藤    マウス    1500   2    3000
35  100 2022-07-09  テスト１株式会社  佐藤     PC  100000   3  300000

In [6]:
# 完成版

from glob import glob
import pandas as pd

files=glob("売上一覧_*.xlsx")

df_concat=pd.DataFrame()

for file in files:
    df_tantou=pd.read_excel(file,sheet_name="Sheet1")
    df_concat=pd.concat([df_concat,df_tantou])

df_concat.sort_values("No.").to_excel("売上一覧_結合.xlsx",index=False)